services:
  elasticsearch:
    image: elasticsearch:2.4
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    command: elasticsearch -Des.index.max_result_window=50000
    restart: always

  keyrock:
    image: fiware/idm:7.0.2
    environment:
      - DATABASE_HOST=mysql
    ports:
      - '3000:3000'
    restart: always

  memcached:
    image: memcached:1
    command: memcached -m 2048m
    restart: always

  mysql:
    image: mysql/mysql-server:5.7.21
    environment:
      - MYSQL_ROOT_PASSWORD=idm
      - MYSQL_ROOT_HOST=%
    restart: always
  nginx:
    image: nginx:latest
    depends_on:
      - wirecloud
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - wirecloud-static:/var/www/static:ro
    ports:
      - '80:80'
    restart: always

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=wirepass # Change this password!
    restart: always

  wirecloud:
    image: fiware/wirecloud:latest
    depends_on:
      - elasticsearch
      - memcached
      - postgres
    volumes:
      - wirecloud-data:/opt/wirecloud_instance/data
      - wirecloud-static:/var/www/static
    environment:
      - DEBUG=False
      # - DEFAULT_THEME=wirecloud.defaulttheme
      - DB_HOST=postgres
      - DB_PASSWORD=wirepass # Change this password!
      - FORWARDED_ALLOW_IPS=*
      - ELASTICSEARCH2_URL=http://elasticsearch:9200/
      - MEMCACHED_LOCATION=memcached:11211
      - FIWARE_IDM_SERVER=${FIWARE_IDM_SERVER}
      - SOCIAL_AUTH_FIWARE_KEY=${SOCIAL_AUTH_FIWARE_KEY}
      - SOCIAL_AUTH_FIWARE_SECRET=${SOCIAL_AUTH_FIWARE_SECRET}
    restart: always

volumes:
  elasticsearch-data:
  postgres-data:
  wirecloud-data:
  wirecloud-static:
